# Background and foreground colors
background = #0e1114
foreground = #e4edf2

# Standard colors
palette = 0=#0e1114
palette = 1=#277789
palette = 2=#7089a4
palette = 3=#d1e1e9
palette = 4=#86a8cc
palette = 5=#9eafe2
palette = 6=#abd9ec
palette = 7=#d0d9de

# Bright colors
palette = 8=#5c646d
palette = 9=#4bd5ec
palette = 10=#9ecdde
palette = 11=#dbeff9
palette = 12=#c0d3ff
palette = 13=#b9aef8
palette = 14=#90e7fe
palette = 15=#f0f4f6
