background            #0e1114
foreground            #e4edf2

# black
color0  #0e1114
color8  #5c646d

# red
color1  #277789
color9  #4bd5ec

# green
color2  #7089a4
color10  #9ecdde

# yellow
color3  #d1e1e9
color11  #dbeff9

# blue
color4  #86a8cc
color12  #c0d3ff

# magenta
color5  #9eafe2
color13  #b9aef8

#cyan
color6  #abd9ec
color14  #90e7fe

#white
color7  #d0d9de
color15  #f0f4f6


